In [11]:
import numpy as np

# Example ndarray
my_array = np.array([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]],
                     [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]]])

# Compute mean along axis 0 (columns)
mean_along_axis_0 = np.mean(my_array, axis=0)

# Compute mean along axis 1 (rows)
mean_along_axis_1 = np.mean(my_array, axis=1)

mean_along_axis_2 = np.mean(my_array, axis=2)

print("Mean along axis 0 (columns):", mean_along_axis_0)
print("Mean along axis 1 (rows):", mean_along_axis_1)
print("Mean along axis 2 (rows):", mean_along_axis_2)

Mean along axis 0 (columns): [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Mean along axis 1 (rows): [[5.5 6.5 7.5]
 [5.5 6.5 7.5]]
Mean along axis 2 (rows): [[ 2.  5.  8. 11.]
 [ 2.  5.  8. 11.]]


In [10]:
my_array.shape

(2, 4, 3)